# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OST_PERF_HISTORY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepoint', models.DateTimeField(verbose_name=b'date published')),
                ('ost', models.CharField(max_length=7)),
                ('ip', models.CharField(max_length=15)),
                ('write_bytes', models.BigIntegerField()),
                ('throughput', models.BigIntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
