# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OST_PERF_HISTORY',
            new_name='ostPerfHistory',
        ),
        migrations.AlterModelTable(
            name='ostperfhistory',
            table='OST_PERF_HISTORY',
        ),
    ]
